# Generated by Django 4.0.3 on 2022-06-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_categorie_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='title',
        ),
    ]
